' *************************************************************************
' **                         Color Section                               **
' *************************************************************************
' Days
!$CLOSED_BK = lightgray
'!$CLOSED_BK = green
!$CLOSED_LINE = white

' Task
!$ALTERNATIVE_COLOR =  Aqua/Blue
!$DONE_COLOR = green
!$TASK_FONT_COLOR = black
!$UNDONE_COLOR = orange

' Legend
!$LEGEND_COLOR = gray/white
!$LEGEND_FONT = blue
!$LEGEND_LINE = gray

' Milestone
!$MILESTONE_COLOR_BK = gold/green
!$MILESTONE_COLOR_FONT = blue
!$MILESTONE_COLOR_LINE = red

' Days
!$HOLIDAY_COLOR = lightgray
!$TODAY_COLOR =  yellow

' Path
!$CRITICAL_PATH_COLOR = red
!$NORMAL_PATH_COLOR = lightblue

' Note
!$NOTE_COLOR_BK = "#FBDB65"/"#FFFFFF"
!$NOTE_COLOR_FONT = black
!$NOTE_COLOR_LINE = black

' Separator
!$SEPARATOR_COLOR_BK = gray/white
!$SEPARATOR_COLOR_FONT = blue
!$SEPARATOR_COLOR_LINE = blue

' Time line
!$TIMELINE_COLOR = gray/lightgray

' Title
!$TITLE_FONT = blue