' meu_estilo.puml

skinparam backgroundColor green
skinparam shadowing false

skinparam class {
  BackgroundColor LightYellow
  BorderColor Black
  FontColor Black
  FontSize 14
}

skinparam note {
  BackgroundColor LightBlue
  BorderColor Blue
  FontColor Blue
  FontSize 12
}
